# Generated by Django 5.2.3 on 2025-06-18 12:19

import app.attachments.models
import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(access_key='minioadmin', bucket_name='subhub', default_acl='private', endpoint_url='http://minio:9000', secret_key='minioadmin', signature_version='s3v4'), upload_to=app.attachments.models.upload_to_attachments, verbose_name='Белые зубы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
