# Generated by Django 5.2.3 on 2025-06-18 13:02

import app.attachments.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(access_key='minioadmin', bucket_name='subhub', default_acl='private', endpoint_url='http://minio:9000', secret_key='minioadmin', signature_version='s3v4'), upload_to=app.attachments.models.upload_to_attachments, verbose_name='Вложения'),
        ),
    ]
