# Generated by Django 5.2.3 on 2025-06-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_user_id',
            field=models.BigIntegerField(default=234, unique=True, verbose_name='Telegram ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tg_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username'),
        ),
    ]
