# Generated by Django 5.2.3 on 2025-06-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_tg_first_name_user_tg_last_name_user_tg_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_user_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_username',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Telegram username'),
        ),
    ]
