# Generated by Django 5.2.3 on 2025-06-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
