# Generated by Django 5.2.3 on 2025-06-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_tg_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Администратор'), ('user', 'Пользователь')], default='user', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
