# Generated by Django 5.2.3 on 2025-06-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
    ]
