# Generated by Django 5.2.3 on 2025-07-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Автор'), ('user', 'Пользователь')], default='user', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
