# Generated by Django 5.2.3 on 2025-06-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tagpost_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='user',
            new_name='author',
        ),
    ]
