# Generated by Django 5.2.3 on 2025-06-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_level_currency_leveluser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='name',
            new_name='title',
        ),
    ]
