# Generated by Django 5.2.3 on 2025-06-18 12:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0002_level_currency_leveluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый пост', max_length=1024, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('can_comment', models.BooleanField(default=True, verbose_name='Комменатрии включены?')),
                ('is_ads', models.BooleanField(default=False, verbose_name='Реклама?')),
                ('support_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная сумма поддержки')),
                ('currency', models.CharField(choices=[('RUB', 'Рубль')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('is_pin', models.BooleanField(default=False, verbose_name='Закреплена?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level', verbose_name='Уровень')),
            ],
        ),
    ]
